name: CI

on:
  push:
  workflow_dispatch:

jobs:
  linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Vagrant & VirtualBox
        shell: bash
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install -y virtualbox vagrant
      - name: Checkout
        uses: actions/checkout@v6
      - run: |
          cd vagrant
          vagrant up --provision
  macOS-arm64:
    runs-on: macOS-latest
    steps:
      - name: Set up Vagrant & VirtualBox
        run: |
          brew install virtualbox vagrant
      - name: Checkout
        uses: actions/checkout@v6
      - run: |
          cd vagrant
          vagrant up --provision
  windows-amd64:
    runs-on: windows-latest
    steps:
      - name: Set up Vagrant & VirtualBox
        shell: cmd
        run: |
          winget Oracle.VirtualBox Hashicorp.Vagrant
      - name: Checkout
        uses: actions/checkout@v6
      - run: |
          cd vagrant
          vagrant up --provision
