name: CI

on:
  push:
  workflow_dispatch:

jobs:
  windows-amd64:
    runs-on: windows-latest
    steps:
      - name: Set up Vagrant & VirtualBox
        shell: cmd
        run: |
          winget install Oracle.VirtualBox Hashicorp.Vagrant --silent --accept-source-agreements --accept-package-agreements
      - name: Checkout
        uses: actions/checkout@v6
      - run: |
          cd vagrant
          vagrant up --provision
